config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :articles do
	  resources :comments
  end

  resources :shedules

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
 
   has_many  :comments, dependent: :destroy
   validates :title, presence: true, length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/shedule.rb
class Shedule < ActiveRecord::Base
  belongs_to :user
  validates  :type_shedule, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :shedules

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  #http_basic_authenticate_with name: "slaff", password: "123", except: [:index, :show]

  def new
    @article = Article.new
  end

  def update
    @article = Article.find(params[:id])
 
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end
 
  def edit
    @article = Article.find(params[:id])
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
 
    redirect_to articles_path
  end

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def create

    @article = Article.new(article_params)

    if @article.save
	    redirect_to @article
    else
	    render 'new'
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :text) 
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  #http_basic_authenticate_with name: "slaff", password: "123", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
 
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
  
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end

end

app/controllers/shedules_controller.rb
class ShedulesController < ApplicationController

  before_filter :authenticate_user!, except: [:show, :index]
  before_filter :find_user,          only:   [:index, :create, :update, :edit, :destroy, :show]

  def new
    @shedule = Shedule.new
  end

  def update

    if @shedule.update(shedule_params)
      redirect_to @shedule
    else
      render 'edit'
    end
  end

  def edit
  end

  def destroy

    @shedule.destroy

    redirect_to shedules_path
  end

  def index
    @shedules = @user.shedules
  end

  def show
  end

  def create

    @shedule = @user.shedules.create(shedule_params)

    if @shedule.save
      redirect_to @shedule
    else
      render 'new'
    end
  end

  private

    def find_user
      @user = User.where(id: current_user.id).first
      @shedule = @user.shedules.where(id: params[:id]).first
    end

    def shedule_params
      params.require(:shedule).permit(:type_shedule, :favorite_town_to, :favorite_town_from)
    end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  before_filter :authenticate_user!, expect: [:index]
  before_filter :find_user,          only:   [:index]

  def index

    if user_signed_in?

      @shedule_type = @shedules.pluck(:type_shedule).first
      #@rss_feed = RSSClass.new.read_rss('http://0.tqn.com/6/g/ruby/b/rss2.xml')
      @rss_feed = RSSClass.new.read_rss('http://news.yandex.ru/galleries.rss')
      #@lastfm = LastfmClass.new.get_events
      #lasttm_test = Hash.from_xml(@lastfm)
      #@my_json = lasttm_test
      #@images = ImageClass.new.get_images(@shedule_type) if @shedule_type

    end

  end

  private

    def find_user
      @user = User.where(id: current_user.id).first
      @shedules = @user.shedules.where(user_id: current_user.id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_comment.html.erb
<p>
<strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
    
   
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>
 
<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1> 
<table>
  <tr>
    <th>Time created</th>
    <th>Title</th>
    <th>Text</th>
  </tr>
 <% @articles.each do |article| %>
  <tr>
    <td><%= article.created_at %></td>
    <td><%= article.title %></td>
    <td><%= article.text %></td>
    <td><%= link_to 'Show', article_path(article) %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Destroy', article_path(article),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <td><%= 'Comments: ' + article.comments.count.to_s %></td>
  </tr>
 <% end %>
  
</table>


<%= link_to 'New article', new_article_path %>
<p><%= link_to 'Home', controller: 'welcome' %></p>

app/views/articles/new.html.erb
<h1> New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p><%= @article.created_at %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<h2>Comments</h2>
<%= render @article.comments %>

<h2>Add a comment:</h2>
<%= render "comments/form" %>

<%= link_to 'Back', articles_path %>
| <%= link_to 'Edit', edit_article_path(@article) %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
 
<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Created for educational
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", '#' %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "MyAssistant", '#', id: "logo" %>
      <nav>
        <ul class="nav navbar-nav pull-right">
          <li><%= link_to "Home", root_path %></li>

          <% if user_signed_in? %>
              <li><p class = "navbar-text"><%= current_user.email %></p></li>
            <li><%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>
          <% else %>
            <li><%= link_to "Log in", new_user_session_path %></li>
            <li><%= link_to "Register", new_user_registration_path %></li>
          <% end %>

          <%#= link_to "Help",    '#' %>

        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <%= render 'layouts/shim' %>

</head>
<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= render 'layouts/header' %>

<div class="container">

  <%= yield %>
  <%= render 'layouts/footer' %>

</div>
</body>
</html>

app/views/shedules/_comment.html.erb
<p>
<strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

app/views/shedules/_form.html.erb
<%= form_for @shedule do |f| %>
  <% if @shedule.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@shedule.errors.count, "error") %> prohibited
      this shedule from being saved:</h2>
    <ul>
    <% @shedule.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

    <div class="row">
      <div class="col-md-4">
          <p>
            <%= f.label :type_shedule %><br>
            <%= f.text_field :type_shedule %>
          </p>

          <p>
            <%= f.label :favorite_town_from %><br>
            <%= f.text_field :favorite_town_from %>
          </p>

          <p>
            <%= f.label :favorite_town_to %><br>
            <%= f.text_field :favorite_town_to %>
          </p>

          <p>
            <%= f.submit %>
          </p>
      </div>
    </div>
<% end %>

app/views/shedules/edit.html.erb
<h1>Editing shedule</h1>
 
<%= render 'form' %>

<%= link_to 'Back', shedules_path %>

app/views/shedules/index.html.erb
<h1>Listing shedules</h1> 
<table>
  <tr>
    <p><%= "#{current_user.email}, #{current_user.id}"   %></p>
  </tr>

 <% @shedules.each do |shedule| %>
  <tr>
    <td><%= shedule.user_id %></td>
    <td><%= shedule.created_at %></td>
    <td><%= shedule.type_shedule %></td>
    <td><%= shedule.favorite_town_from %></td>
    <td><%= shedule.favorite_town_to %></td>
    <td><%= link_to 'Show', shedule_path(shedule) %></td>
    <td><%= link_to 'Edit', edit_shedule_path(shedule) %></td>
    <td><%= link_to 'Destroy', shedule_path(shedule),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
 <% end %>
  
</table>


<%= link_to 'New shedule', new_shedule_path %>
<p><%= link_to 'Home', controller: 'welcome' %></p>

app/views/shedules/new.html.erb
<h1> New Shedule</h1>

<%= render 'form' %>



<%= link_to 'Back', shedules_path %>

app/views/shedules/show.html.erb
<p><%= @shedule.created_at %></p>

<p>
  <strong>Type:</strong>
  <%= @shedule.type_shedule %>
</p>
 
<p>
  <strong>Town from:</strong>
  <%= @shedule.favorite_town_from %>
</p>

<p>
  <strong>Town to:</strong>
  <%= @shedule.favorite_town_to %>
</p>


<%= link_to 'Back', shedules_path %>
| <%= link_to 'Edit', edit_shedule_path(@shedule) %>

app/views/static_pages/about.html.erb
<h1>About project</h1>

<dl>
  <dt><p class="lead">Проект MyAssistant это учебный проект.</p></dt>
    <dd>
      <p>
      В нем используется api.Yandex для отображения расписания транспорта Также будет реализовано отображение событий из Google.Calendar.
      В будущем проект будет включать дополнительные возможности: быстрый перевод текста, отображение картинок по заданному слову и так далее.
      </p>
    </dd>
  <p></p>
  <dt><p class="lead">MyAssistant project is an educational project.</p></dt>
  <dd>
      It is used to display schedules api.Yandex transport There will also be implemented display events from Google.Calendar.
      In the future, the project will include additional features such as a quick translation of the text, images, for a given word, and so on.
  </dd>
</dl>

app/views/static_pages/help.html.erb
<h1>Help...</h1>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", '#', class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/welcome/index.html.erb
<% if user_signed_in? %>

  <h3><%= link_to 'My Articles', controller: 'articles' %></h3>
  <h3><%= link_to 'My Shedules', controller: 'shedules' %></h3>



    <% if @rss_feed %>
    <p>RSS:</p>
    <%#= @rss_feed[0].title %>
    <% @rss_feed.each do |item| %>
    <%= link_to item.title, item.url %><br/>

    <% end %>
    <% end %>


    <% if @lastfm %>
    <p>Last.FM events:</p>
    <% @lastfm.each do |item| %>
        <p><%= link_to item[:title], item[:url] %></p>
    <% end %>
    <% end %>

<% else %>

    <div class="center hero-unit">
      <h1>Welcome to the MyAssistant App</h1>

      <h2>
        This is the home page for my project on Rails:
        <a href="https://github.com/SlaffM/MyAssistant">#Github</a>
      </h2>

      <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-primary" %>
    </div>

    <%#= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

<% end %>